### PR TITLE
Update make_messages.py

### PR DESCRIPTION
**Pull request by pescheck-bram**
Because it is not working with opnly the msgmerge_options anymore.

### CODE REVIEW

**Comment by uri-rodberg** [comment]
> Because it is not working with opnly the msgmerge_options anymore.

Hi @pescheck-bram,

Thank you for this PR. Can you explain why is this PR needed and what is not working?

Also, did it work before? And when (which Django version) did it stop working?

**Comment by pescheck-bram** [comment]
To extend the `makemessages` command in Django and add a new option (`--no-fuzzy-matching`), you need to follow these steps:

1. **Create a Custom Management Command:**
   
   You have already defined a new command class that inherits from `makemessages.Command`. This is the correct approach. Your custom command class modifies the `msgmerge_options` to include the `--no-fuzzy-matching` option.

2. **Modify the `add_arguments` Method:**

   You need to override the `add_arguments` method in your custom command class to add the new option. This method is responsible for defining the command-line options for your management command.

   Here is an example of how to modify the `add_arguments` method:

   ```python
   from django.core.management.commands import makemessages

   class Command(makemessages.Command):
       msgmerge_options = makemessages.Command.msgmerge_options + ["--no-fuzzy-matching"]

       def add_arguments(self, parser):
           super().add_arguments(parser)
           parser.add_argument(
               '--no-fuzzy-matching',
               action='store_true',
               help='Do not use fuzzy matching in msgmerge.',
           )
   ```

   In this modification, we call `super().add_arguments(parser)` to include all the existing arguments from the base `makemessages` command, and then we add the `--no-fuzzy-matching` argument.

You need the add_arguments to call the super or else it will not add the argument.

**Comment by uri-rodberg** [comment]
Thank you, I understand. I merged your PR and I will check if it works.

**Comment by uri-rodberg** [comment]
Hi @pescheck-bram. Due to issue https://github.com/speedy-net/speedy-net/issues/32, I decided to revert this PR.

**Pull request merged**
